name: Compile stockfish workflow

on:
  workflow_dispatch:

permissions: write-all

jobs:
  Stockfish:
    name: Compile stockfish
    runs-on: ubuntu-20.04
    env:
      COMPILER: armv7a-linux-androideabi21-clang++
      COMP: ndk
      CXXFLAGS: "-Werror"
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Download required linux packages
        run: |
          sudo apt update
          sudo apt-get remove sqlite3
          sudo apt-get remove libsqlite3-dev          
          sudo apt install -y expect valgrind g++-multilib qemu-user
          sudo apt-get install -y gcc-arm-linux-gnueabi

      - name: Fetch sqlite3 src files
        run: |  
          wget https://www.sqlite.org/2023/sqlite-autoconf-3430200.tar.gz
          tar xvzf sqlite-autoconf-3430200.tar.gz
              
      - name: Configure sqlite3
        run: |
          cd sqlite-autoconf-3430200/
          ./configure --host=arm-linux
          
      - name: Make sqlite3
        run: |
          cd sqlite-autoconf-3430200/
          make

      - name: Install sqlite3
        run: |
          cd sqlite-autoconf-3430200/
          sudo make install          

      - name: Download the used network from the fishtest framework
        run: |
          make net
    
      - name: armv7 build
        run: |
          export LDFLAGS="-Wno-unused-command-line-argument -L /usr/local/lib/ -lsqlite3 -static -static-libgcc"
          make clean
          make -j2 ARCH=armv7 build


  
