name: Compile stockfish workflow

on:
  workflow_dispatch:
  permissions: write-all

jobs:
  Stockfish:
    name: Compile stockfish
    runs-on: ubuntu-20.04
    env:
      COMPILER: armv7a-linux-androideabi21-clang++
      COMP: ndk
      CXXFLAGS: "-Werror"
    defaults:
      run:
        working-directory: src
        shell: "'bash {0}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Download required linux packages
        run: |
          sudo apt update
          sudo apt install expect valgrind g++-multilib qemu-user

      - name: Download the used network from the fishtest framework
        run: |
          make net
    
      - name: armv7 build
        run: |
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export LDFLAGS="-static -Wno-unused-command-line-argument"
          make clean
          make -j2 ARCH=armv7 build


  
