name: Compile stockfish workflow

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  - name: Checkout
    uses: actions/checkout@v4
  - name: compiling test
    runs-on: ${{ matrix.config.os }}
    env:
      COMPILER: ${{ matrix.config.compiler }}
      COMP: ${{ matrix.config.comp }}
      CXXFLAGS: "-Werror"
    strategy:
      matrix:
      - {
        name: "Ubuntu 20.04 NDK armv8",
        os: ubuntu-20.04,
        compiler: aarch64-linux-android21-clang++,
        comp: ndk,
        run_armv8_tests: true,
        shell: 'bash {0}'
        }
    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v2
      - name: Test armv8 build
        run: |
        export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export LDFLAGS="-static -Wno-unused-command-line-argument"
        make clean
        make -j2 ARCH=armv8 build

  
