name: Compile sqlite3 workflow

on:
  workflow_dispatch:

permissions: write-all

jobs:
  sqlite3:
    name: Compile sqlite3
    runs-on: ubuntu-20.04
    env:
      COMPILER: armv7a-linux-androideabi21-clang++
      COMP: ndk
      CXXFLAGS: "-Werror"
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Download required linux packages
        run: |
          sudo apt update
          sudo apt install -y expect valgrind g++-multilib qemu-user
          sudo apt-get install gcc-arm-linux-gnueabi          

      - name: Fetch sqlite3 src files
        run: |  
          wget https://www.sqlite.org/2023/sqlite-autoconf-3430200.tar.gz
          tar xvzf sqlite-autoconf-3430200.tar.gz
              
      - name: Configure sqlite3
        run: |
          cd sqlite-autoconf-3430200/
          ./configure --host=arm-linux CC=/usr/bin/arm-linux-gnueabi-gcc
          
      - name: Make sqlite3
        run: |
          cd sqlite-autoconf-3430200/
          make

      - name: Install sqlite3
        run: |
          cd sqlite-autoconf-3430200/
          make install
          
