name: Compile sqlite3 workflow

on:
  workflow_dispatch:

permissions: write-all

jobs:
  sqlite3:
    name: Compile sqlite3
    runs-on: ubuntu-20.04
    env:
      COMPILER: armv7a-linux-androideabi21-clang++
      COMP: ndk
      CXXFLAGS: "-Werror"
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Download required linux packages
        run: |
          sudo apt update
          sudo apt install -y gcc-9-arm-linux-gnueabi gcc-arm-linux-gnueabi expect valgrind g++-multilib qemu-user

      - name: Fetch src files
        run: |
          wget https://www.sqlite.org/2023/sqlite-autoconf-3430200.tar.gz
          tar xvzf sqlite-autoconf-3430200.tar.gz
              
      - name: Compile
        run: |
          cd sqlite-autoconf-3430200/
          ./configure --host=arm-linux
          
